name: Check Rebar Dependencies

on: [pull_request]

jobs:
  check_deps_integrity:
    strategy:
      matrix:
        container:
          - "emqx/build-env:erl23.2.7.2-emqx-2-ubuntu20.04"
          - "emqx/build-env:erl24.0.1-emqx-1-ubuntu20.04"

    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2
      - name: Run check-deps-integrity.escript
        run: ./scripts/check-deps-integrity.escript
